version: '3.8'

services:
  django:
    build: .
    container_name: devgonzalezf_django
    ports:
      - "8000:8000"
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: devgonzalezf_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certs:/etc/letsencrypt
    networks:
      - backend

networks:
  backend:
    driver: bridge
