version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: devgonzalezf_django
    ports:
      - "8000:8000"
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: devgonzalezf_nginx
    volumes:
      - ./certs:/etc/letsencrypt
      - ./webroot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

networks:
  backend:
    driver: bridge
