version: '3.8'

services:
  django:
    build: .
    container_name: devgonzalezf_django
    ports:
      - "8000:8000"
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: devgonzalezf_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
