# Generated by Django 5.0.6 on 2024-06-15 16:07

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('institucion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('anio', models.CharField(max_length=4)),
                ('categoria', models.CharField(max_length=50)),
                ('certificado', models.URLField(max_length=500)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('github', models.URLField(max_length=500)),
                ('linkedin', models.URLField(max_length=500)),
                ('email', models.EmailField(max_length=50)),
                ('curriculum', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tecnologias', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('repositorio', models.URLField(max_length=500)),
                ('view_live', models.URLField(max_length=500)),
                ('iconos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
    ]
