# Generated by Django 5.0.6 on 2024-06-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
