# Generated by Django 5.0.6 on 2024-06-18 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_softskills_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='softskills',
            name='categoria',
        ),
    ]
