# Generated by Django 5.0.6 on 2024-06-22 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_softskills_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='telefono',
        ),
    ]
