# Generated by Django 5.0.6 on 2024-07-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_contacto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaciones',
            name='descripcion',
            field=models.JSONField(default=list),
        ),
    ]
