# Generated by Django 5.0.6 on 2024-07-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_certificaciones_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaciones',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
